### ISSUE TITLE
CDash Server

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#1]
Setup a CDash server for testing DTK locally. Link this server to this github repo for continuous/nightly testing of the library.

**Comment by sslattery** [comment]
Lets put the new Travis CI work here. We will close when that is setup.

**Comment by dalg24** [comment]
c.f. PR #37

**Comment by dalg24** [comment]
New server is hosted [here](http://jupyterdocker.ornl.gov/CDash/index.php?project=DataTransferKit)

**Comment by sslattery** [comment]
- Will explore other options besides CDash to display results from CI.

- Want to target a single docker build for CI with all adapters.

- Primary task is to reduce build times.

**Comment by sslattery** [comment]
@dalg24 Can we close this? Are you happy with docker/Travis/Jenkins or should we leave this open for more work?
