### ISSUE TITLE
DTK configuration for spack

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#103]
[Spack](http://computation.llnl.gov/projects/spack-hpc-package-manager) ([github](https://github.com/LLNL/spack)) is a tool for managing software tools versioning and dependencies.

HPC platforms are going to install Spack by default (@Rombur reference?), it may be a good idea to provide a configuration for it. The issue is that DTK is currently built inside the Trilinos, so it is unclear of the best way to approach this.

It should not be too hard to do, though. For instance, take a look at [Trilinos configuration file](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/trilinos/package.py).

**Comment by Rombur** [comment]
I don't remember where I saw that spack will be used for summit and sierra but here is the reference for trinity http://insidehpc.com/2016/08/spack/

**Comment by sslattery** [comment]
https://groups.google.com/forum/#!topic/spack/DRaOJQUn-TQ

**Comment by aprokop** [comment]
Add spack installation docs similar to [Cap docs](http://cap.readthedocs.io/en/latest/install.html?highlight=spack#third-party-libraries)

**Comment by aprokop** [comment]
The TPLs Spack documentation is in #223.

**Comment by aprokop** [comment]
Added a PR to upstream inclusion of DTK spack build in llnl/spack#4304

**Comment by aprokop** [comment]
PR was merged.
