### ISSUE TITLE
Github labels and [WIP] semantics

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#105]
The conversation was started in #104. The conversation so far:

sslattery: @aprokop is this WIP? isn't it being actively reviewed?
aprokop: It is [WIP] because it is not a final state of patches. Unless I understand WIP incorrectly.
sslattery: I interpreted WIP as something that is still being actively developed. Once removed it is ready for review and fixes per the reviewer comments
aprokop: Then I think we need three states:
1. Work has been started but not finished
2. Work has been finished and patches are ready for review, but they may need more work
3. Work got review approval and satisfies all criteria. Merge.

The issue I see with missing 2 is that there is no clear indication whether the patches have been cleaned up. So, somebody may see that a PR has been reviewed and go ahead and merge while an authors is rebasing and cleaning up.
sslattery:I think if the patches haven't been fixed then it simply isn't merged yet. So if the reviewer thinks 2 is done and the PR can move to 3 then it is merged and closed
sslatery: Thats also what the need review tag is for

**Comment by aprokop** [comment]
If I review a branch, and find no issues, do I remove "need review"? If somebody else look at this branch and find issues with it, do we rely on that person to put "need review" label back on?

**Comment by sslattery** [comment]
i would say it needs review until it is merged. i guess we don't have a multiple reviewer policy

**Comment by sslattery** [comment]
We have discussed and come to an agreement
