### ISSUE TITLE
STK adapter does not automatically pull DTK_C_API

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#126]
The build fails with the following config:
```bash
ARGS=(
    -D CMAKE_BUILD_TYPE=RELEASE

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-dtk/

    -D BUILD_SHARED_LIBS="$SHARED"

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=OFF
    -D CMAKE_CXX_FLAGS="-g -Wall -Wextra -Wno-unused-parameter $CXX_FLAGS_COMPILER_SPECIFIC $SYSTEM_HEADERS"
    -D Trilinos_ENABLE_SHADOW_WARNINGS=ON

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON

    -D TPL_ENABLE_Boost=OFF
    -D TPL_ENABLE_BoostLib=ON
    -D TPL_ENABLE_Libmesh=OFF
    -D TPL_ENABLE_MOAB=OFF

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit"

    -D Trilinos_ENABLE_Tpetra=ON
        -D Tpetra_INST_INT_UNSIGNED_LONG=ON
        -D Tpetra_INST_INT_LONG_LONG=OFF
    -D Trilinos_ENABLE_DataTransferKit=ON
        -D DataTransferKit_ENABLE_YouCompleteMe=ON
        -D DataTransferKit_ENABLE_ClangFormat=ON
        -D DataTransferKit_ENABLE_DBC=ON
        -D DataTransferKit_ENABLE_TESTS=ON
        -D DataTransferKit_ENABLE_EXAMPLES=ON
    -D Trilinos_ENABLE_DataTransferKitSTKMeshAdapters=ON
    -D Trilinos_ENABLE_STK=ON
        -D Trilinos_ENABLE_STKTopology=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=OFF
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )

cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS ../../
```
The failure is like this:
```
../../DataTransferKit/packages/Adapters/STKMesh/example/mesh_deformation.cpp:50:23: fatal error: DTK_C_API.h: No such file or directory
 #include "DTK_C_API.h"
```
The problem is that DTK_C_API adapter is not being built despite being specified in the STK adapter's cmake dependencies list. This may be related to #109, but it passes the configure just fine, it fails during the build.

Switching `ASSERT_MISSING_PACKAGES=ON` does not help.

**Comment by sslattery** [comment]
Did you try this with the master branch?

**Comment by Rombur** [comment]
Why do you turn off Boost but turn on BoostLib?

**Comment by sslattery** [comment]
yeah if you turn off boost it will turn off the c api

**Comment by aprokop** [comment]
@sslattery  yes, this is with the master branch, and it has the October 24th commit in cmake

@Rombur I turned it as the config without it was failing and it asked me to turn it on. It did not ask me to turn on Boost, and the config passed without it.

@sslattery Then we need to catch this case.

**Comment by Rombur** [comment]
IIRC Boost is for the header-only part of the library, while BoostLib is for the compiled part of the library. So if BoostLib is on Boost should also be on.

**Comment by aprokop** [comment]
I can confirm that explicitly turning on 
```
-D TPL_ENABLE_BOOST=ON
```
in the configure script fixes it.

**Comment by sslattery** [comment]
So the C adapters are listed as a test requirement. Are you trying to build the tests? If so the build system should have turned off the tests or failed at the configure if it was turned off.

**Comment by aprokop** [comment]
Yes, I was trying to build the tests and examples with `-D DataTransferKit_ENABLE_EXAMPLES=ON`

**Comment by sslattery** [comment]
OK - I wonder why TriBITS didn't turn them off or fail then? Thats why we set up these package dependencies...

**Comment by dalg24** [comment]
Remove `-D Trilinos_ASSERT_MISSING_PACKAGES=OFF` (c.f. discussion with Ross on #109).
How long is this silly mistake going to hurt us...

**Comment by sslattery** [comment]
oh yeah - keep forgetting about that...

**Comment by aprokop** [comment]
@dalg24 Actually, I think I tried with that and it did not help in this case.

**Comment by aprokop** [comment]
Can confirm that removing `Trilinos_ASSERT_MISSING_PACKAGES` or switching it to `ON` does **NOT** solve the problem.

**Comment by aprokop** [comment]
If I add `DataTransferKitC_API` to STKMesh's `LIB_REQUIRED_PACKAGES` it correctly fails with
```
   *** ERROR: Setting Trilinos_ENABLE_DataTransferKitSTKMeshAdapters=OFF which was 'ON' because DataTransferKitSTKMeshAdapters has a required library dependence on disabled package DataTransferKitC_API!
```

**Comment by aprokop** [comment]
I explicitly add
```
-D DataTransferKitSTKMeshAdapters_ENABLE_EXAMPLES=ON
```
it correctly fails to configure with the same error even without `DataTransferKitC_API` in `LIB_REQUIRED_PACKAGES`.

So, I think the problem is the STKMesh's examples are automatically compiled even when they were not configure to do that.

**Comment by aprokop** [comment]
The problem may be more widespread: for instance, Intrepid tests are also compiled even they were not explicitly enabled. The question is: what does `DataTransferKit_ENABLE_EXAMPLES` or `ENABLE_TESTS` do, and how does it play with all the test dependencies?

**Comment by aprokop** [comment]
@bartlettroscoe Ross, does turning on the package EXAMPLES/TESTS on automatically turn on all the subpackage examples/tests? How does dependency resolution work in this case?

**Comment by bartlettroscoe** [comment]
> does turning on the package EXAMPLES/TESTS on automatically turn on all the subpackage examples/tests? How does dependency resolution work in this case?

It depends what you mean by "does turning on the package EXAMPLES/TESTS on automatically turn on all the subpackage examples/tests?"   Can you state a more explicit example?

Not sure if this is related but there is a known defect TriBITSPub/TriBITS#56 but that does not enable more examples/tests.  It just turns on too many upstream packages.  That will get fixed after I can test all of Trilinos safely (see trilinos/Trilinos#482).

I believe that tt is true that if you enable the tests/examples for a given parent package, that automatically enables the tests/examples for all of the subpackages in that parent packages.  I don't see that logic specifically mentioned at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#enable-disable-of-parent-package-is-enable-disable-for-subpackages

**Comment by aprokop** [comment]
@bartlettroscoe Here is the situation at hand, I think it is different from all the issues you mentioned.

DTK has several subpackages in it including STKMesh. Turning on `-D DataTransferKit_ENABLE_EXAMPLES=ON` adds all directories specified with `TRIBITS_ADD_EXAMPLE_DIRECTORIES()` in all the subpackages, so for instance it adds `STKMesh/example`. This is as expected.

However, it seems that this automatic addition bypasses the dependencies checks for examples specified in `STKMesh/cmake/Dependencies.cmake`. If, on the other hand, one explicitly adds `-D DataTransferKitSTKMesh_ENABLE_EXAMPLES=ON` the checks are being done.

This is different from TriBITS/Pub/TriBITS#56 as it has nothing to do with upstream packages, as everything is within the same package. This is also different from the tribits doc as the situation has both parent and subpackages enabled.

**Comment by bartlettroscoe** [comment]
@aprokop, it sounds like this might be a defect in the TriBITS dependency logic.  While this may be different from TriBITSPub/TriBITS#56 it may be strongly related.  What are the exact SHA1 versions of Trilinos and DTK and full configure options that show the different scenarios?

If this is a new defect, then I can likely fix this at the same that I am fixing TriBITSPub/TriBITS#56 (which will be after trilinos/Trilinos#482).

**Comment by aprokop** [comment]
@bartlettroscoe It can be tried with HEAD both Trilinos and DTK. But if you need the exact SHA1 I'm using they are DTK: 21bf6bf and Trilinos: 674cff2.

The configure script is in the beginning of the issue. That configure script does not fail at the configure stage but fails during compilation as it does not properly switch the subpackage on. If you add `-D DataTransferKitSTKMeshAdapters_EXAMPLEs=ON` the configuration will fail.

**Comment by bartlettroscoe** [comment]
Okay, I will take a look.  How urgent is this?  Is there a workaround that you can keep going until I can get to this in the next few days?

**Comment by aprokop** [comment]
It's not urgent. The workaround exists.

**Comment by aprokop** [comment]
@bartlettroscoe Just a ping to see if you had a chance to look at it.

**Comment by bartlettroscoe** [comment]
> Just a ping to see if you had a chance to look at it.

Not yet.  First have to get trilinos/Trilinos#482 done.

**Comment by Rombur** [comment]
Let's close this. We don't have STK adapter anymore.

**Comment by aprokop** [comment]
@Rombur This is not about STK, it's about the fact the subpackage dependencies are not handled properly. I don't know if that only concerns subpackages, or affects packages too.
