### ISSUE TITLE
Create a step-by-step release recipe

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#133]
We should create a release recipe similar to https://github.com/dealii/release-papers/blob/master/release-tasks This way we won't forget a step and anyone will be able to easily do a release.

**Comment by aprokop** [comment]
Wow, that's some long task list 😄

**Comment by Rombur** [comment]
Here is a tentative list. Please add/change the order of the bullet points when you are working on  the release. Hopefully after this release we have a list that can be followed step-by-step.
- [ ] Create a release branch: git branch dtk-X.Y 
- [ ] Update Version.cmake on master
- [ ] Update Version.cmake on the branch: update DataTransferKit_VERSION_STRING and set DataTransferKit_ENABLE_DEVELOPMENT_MODE_DEFAULT to OFF
- [ ] Remove unnecessary files:
  - [ ] docker/jenkins
- [ ] Test the branch with different configurations
- [ ] Check the documentation
  - [ ] doxygen
  - [ ] ReadTheDocs
- [ ] Create the release on Github
- [ ] Push the new doxygen to https://ornl-cees.github.io/DataTransferKit/
- [ ] Add a post that the new release is available to https://ornl-cees.github.io/DataTransferKit/
- [ ] Update the Download post on http://ornl-cees.github.io/DataTransferKit/ to add the new release
- [ ] Update the About post on http://ornl-cees.github.io/DataTransferKit
- [ ] Write a post to dtk-announce google group
```
Title: DTK X.Y has been released

DTK X.Y has been released and can be downloaded at:

http://ornl-cees.github.io/DataTransferKit/download/

If you are currently using DTK, it is strongly encouraged that you switch to the latest stable release download instead of the DTK master branch. Please let us know if you have any questions regarding this version release and our development plans.

Thanks

DTK Team
```
