### ISSUE TITLE
Trilinos 12.10 has been released

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#135]
Trilinos 12.10 has been released. This release may fix the problem we had with STK mesh. So we should update the container and try again.

**Comment by aprokop** [comment]
What is the STK mesh problem? Can you reference it?

**Comment by Rombur** [comment]
I don't remember exactly what the problem is but it is related to this https://github.com/trilinos/Trilinos/issues/62

**Comment by dalg24** [comment]
OK, let's update our base image.  What else would we like to update in it?
I see that:
* NetCDF had a new [maintenance release](http://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-4-1-1).
* Libmesh is working on a [1.1.0 release](https://github.com/libMesh/libmesh/releases).
* Moab has a tagged a [4.9.2 release](https://bitbucket.org/fathomteam/moab/downloads?tab=tags).

**Comment by aprokop** [comment]
Fixed in #139.
