### ISSUE TITLE
CII best practices

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#137]
I've been listening to ChangeLog podcast recently about Core Infrastructure Initiative. In short, they propose a list of things a project should follow. This was mostly for core projects, but I thought that we may find some interesting things to look at. The list of criteria is [here](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md).

One of the things they recommend is doing static and dynamic analysis of the code. We don't do that, I think.

**Comment by dalg24** [comment]
We can probably add `cppcheck` to our CI.
As far as dynamic analysis, `valgrind` is already in our Docker image.  Another option would be to add option flags to the compiler to use the address sanitizer.

**Comment by sslattery** [comment]
Will do dynamic analysis with sanitize flags and valgrind, each in a separate build on master with frequency off builds to be determined. Will also do dynamic analysis of test coverage.

For static analysis we will look at cppcheck but will need a plan to address errors in output; also known to have false positives. Will also look at coverity

@Rombur will take a look at adding sanitize flags to build and report back on errors and run times

@ssslattery will look at how coverage testing is setup in cap and report back

@sslattery will run a few tests with valgrind and will look at CASL valgrind suppression file. Will also look at how valgrind tests are currently run in CASL. There may be a test prefix capability.

**Comment by sslattery** [comment]
I really like the coverage [output](https://codecov.io/gh/ORNL-CEES/Cap) - I think this would be really helpful

**Comment by sslattery** [comment]
Ran a few of the operator tests in the docker with valgrind. Clean so far except for MPI...

**Comment by sslattery** [comment]
See #153 for @Rombur results on sanitize

**Comment by sslattery** [comment]
@rombur will open new issue on sanitize builds in CI

**Comment by aprokop** [comment]
Just giving up on this.
