### ISSUE TITLE
Using git commit and like in a docker image messes up file ownership

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#145]
I got tripped by the following: running Docker using `docker-compose` in `DataTransferKit/docker`, editing and committing files inside the container changed/created files with root permissions in `.git/objects`. Not fun.

I don't know of a good solution for this. A workaround for situations when one does not have a root/sudo on the machine is to change the permissions back in the container.

**Comment by dalg24** [comment]
Yep, definitely was aware of these side effects.

**Comment by sslattery** [comment]
To address a bash script is needed at entry point of container creating a user with identical name and UID to the user that launched the container. We anticipate problems with permissions that will have to be addressed.

**Comment by aprokop** [comment]
Closing as this is just a very minor inconvenience for Docker newbies.
