### ISSUE TITLE
Allow `clang-format` in addition to `clang-format-3.9`

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#148]
Right now, the test only check for the exact `clang-format-3.9`. So, even if I install clang 3.9, it does not find it if I don't create a `clang-format-3.9` symbolic link.

**Comment by aprokop** [comment]
Can we use some stuff from [here](https://cmake.org/pipermail/cmake/2014-January/056677.html)?

**Comment by dalg24** [comment]
[Here](https://github.com/ORNL-CEES/DataTransferKit/blob/master/cmake/CodeFormat.cmake#L1) is where CMake looks for `clang-format`.  There is no such CMake module as `ClangFormat` so `find_program` is the right approach.  The reason why I did not search for `clang-format` without the version as suffix is that if we detect a version other than 3.9, the output of `check_format_cpp` will be different (even though the style configuration file is the same).  I suppose we could do something like:
```
execute_process(
    ${CLANG_FORMAT_EXECUTABLE} -version
    OUTPUT_VARIABLE CLANG_FORMAT_VERSION
)
if(NOT CLANG_FORMAT_VERSION MATCHES "3.9")
    message(FATAL_ERROR "You must use clang-format version 3.9")
endif()
```
We could also let you specify the path to clang-format when you configure.
