### ISSUE TITLE
Version 2.0.0 Known issues

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#153]
Below are some known issues with DTK version 2.0. Since DTK 2.0 is deprecated, these issues won't be fixed:
 - `BasicEntitySetIterator::begin()` and `BasicEntitySetIterator:end()`: The return type is an object of the base class, `EntityIterator`, but we are returning an object of the derived class. This means that we would need a constructor of the type `EntityIterator(const BasicEntitySetIterator &derived)`. However, this `EntityIterator` object cannot be downcasted to `BasicEntitySetIterator` which is needed in `operator==` and `operator!=`. The right thing to do would be to return a pointer `EntityIterator*` or a reference `EntityIterator&`. Both of these solutions require the `begin` and the `end` iterator to exist outside the functions `begin()` and `end()`.
 - `BasicEntitySetIterator::operator==` and `BasicEntitySetIterator::operator!=`: these functions use a `static_cast` to cast a `EntityIterator` to a `BasicEntitySetIterator` instead of a `dynamic_cast`. Thus, if the `EntityIterator` is not of type `BasicEntitySetIterator`, the code generated is wrong and the code will crash. Because of the implementation of `BasicEntitySetIterator::begin()` and `BasicEntitySetIterator::end()`, we cannot use a `dynamic_cast`. If we do, the compiler will rightfully throw a `std::bad_cast` when using the `begin` or the `end` iterator.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
