### ISSUE TITLE
Configure error when Fortran is not enable

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#160]
Using `-DTrilinos_ENABLE_Fotran=OFF` should disable the fortran api. Right now it produces the following error:
CMake Error: CMake can not determine linker language for target: dtk_fortran_api
CMake Error in DataTransferKit/packages/Adapters/Fortran_API/src/CMakeLists.txt:
  Exporting the target "dtk_fortran_api" is not allowed since its linker
  language cannot be determined

**Comment by aprokop** [comment]
Weird, I always configure with Fortran OFF, but have not seen this error.

**Comment by sslattery** [comment]
i didn't even know that was an option. we should fix the cmake to support that.

**Comment by dalg24** [comment]
I did not list Fortran in the list of dependencies of the Fortran_API...

**Comment by dalg24** [comment]
@aprokop I bet you had that silly `-D Trilinos_ASSERT_MISSING_PACKAGES=OFF` flag at the time.

**Comment by aprokop** [comment]
@dalg24 True. But also, don't you have to enable Fortran_API explicitly in the configuration script?

**Comment by dalg24** [comment]
Here is how to reproduce what @Rombur reported.
```
[container]$ cd $TRILINOS_DIR/DataTransferKit
[container]$ mkdir build && cd build
[container]$ ../scripts/docker_cmake -D Trilinos_ENABLE_Fortran=OFF
```
which yield
```
[...]
-- Configuring done
CMake Error: CMake can not determine linker language for target: dtk_fortran_api
CMake Error in DataTransferKit/packages/Adapters/Fortran_API/src/CMakeLists.txt:
  Exporting the target "dtk_fortran_api" is not allowed since its linker
  language cannot be determined


CMake Error: CMake can not determine linker language for target: dtk_fortran_api
CMake Error in DataTransferKit/packages/Adapters/Fortran_API/src/CMakeLists.txt:
  Exporting the target "dtk_fortran_api" is not allowed since its linker
  language cannot be determined


CMake Error: Cannot determine link language for target "dtk_fortran_api".
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_Fortran_LINK_EXECUTABLE
-- Generating done
-- Build files have been written to: /scratch/source/trilinos/release/DataTransferKit/build
```

**Comment by aprokop** [comment]
I looked at ForTrilinos, and surprisingly they also don't have Fortran dependency in their `Dependencies.cmake`. Not sure why. So I don't even know if you can drive it from Dependencies, or if you have to add logic to the package's `CMakeLists.txt`.
