### ISSUE TITLE
Sanitizers

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#164]
Steps needed to run the sanitizers:
 - [x] create a Docker image similar to `dtk-stack` but compiled using clang
 - [x] add script to compile dtk with the sanitizer flags
 - [x] ignore known issues in DTK
 - [x] use jenkins to run the sanitizers daily or on merge on master

**Comment by aprokop** [comment]
Do we really need a new Docker image, or simply setting `OMPI_MPICC` and `OMPI_MPICXX` would suffice as `clang` is already installed?

**Comment by Rombur** [comment]
I don't think that `clang` is already installed. We just install `clang-format` which in ubuntu can be installed without installing `clang` itself. I am also using the `OpenMP` runtime library from `clang` instead of the one from `gcc`.

**Comment by aprokop** [comment]
Oh, OK, I did not realize it was separated from the clang compiler itself. Still, would it be easier just to update the existing image to also include clang? I would prefer as few images as possible as updating one would mean updating all and keeping them in sync. The size would increase, but I would be OK to pay that price.

**Comment by sslattery** [comment]
@dalg24 what do you think about a single large image vs. multiple smaller images?

**Comment by Rombur** [comment]
We could. The two Dockerfile are almost identical right now. So the plan was to have a `Makefile` that would create the `Dockerfile`. Something like `make gcc_compiler` would create the `Dockerfile` for the `gcc` compiler from `Dockerfile.in`. We could put everything in one image but I am not a fan of mixing compiler.

**Comment by aprokop** [comment]
If you are hesitant of mixing compilers installed by Ubuntu, maybe use Spack?
`spack install gcc`, `spack install llvm`, `spack load gcc`/`spack load llvm`

**Comment by Rombur** [comment]
@aprokop I don't want to use `boost` compiled with `gcc` with `trilinos` compiled with `clang`. Or are you suggesting to have `boost` compiled with `gcc` and `boost` compiled with `clang` in the same image?

**Comment by dalg24** [comment]
@sslattery wrote:
> @dalg24 what do you think about a single large image vs. multiple smaller images?

Unsure at this point.  The main thing is we do not want to maintain many Dockerfile(s) if we can avoid (that good ol' reusability principle).  For the moment we just need one image and we'll be able to advise later.

**Comment by aprokop** [comment]
Oh, I see you problem. I guess the issues is that our Dockerfile actually compiles a lot of stuff itself. Forgot about that. I see you point then. Having two images is fine in that situations as most TPLS would be duplicated for gcc+clang. Spack is still feasible but at a much larger cost.

**Comment by dalg24** [comment]
As much as I'd love to have a Spack recipe to setup the development environment and install the TPLs (c.f. #103), this might be a gigantic pain to implement.

**Comment by aprokop** [comment]
@dalg24 As much as I'd like, I cannot really contradict that.

**Comment by Rombur** [comment]
We will need to decide what triggers the sanitizer. Ideally, we would want to have a second webhook to trigger jenkins but it doesn't look like it's possible :-( Right now the webhook triggers both the experimental and the sanitizer build but since there is only one place to report the result the experimental build overrides the sanitizer build.

**Comment by dalg24** [comment]
We can disable the update of the commit status but keep the trigger.  Does that make sense?

**Comment by Rombur** [comment]
Closed by #177
