### ISSUE TITLE
Add CUDA to Docker

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#172]
CUDA is needed for development and testing. Options include adding CUDA to the existing docker cmake file or creating an extension of that file. Also, several local machine parameters must be respected including the local CUDA version and the local compute hardware capability.

**Comment by aprokop** [comment]
CUDA download typically means accepting some king of licensing agreement. Can you actually distribute images like that?

**Comment by sslattery** [comment]
My plan was to use the CUDA already installed on the hardware - we wouldn't distribute CUDA with the image. So we'll have to a have a way to get the CUDA information from the hardware.

**Comment by sslattery** [comment]
Apparently NVIDIA has a [Docker](https://github.com/NVIDIA/nvidia-docker)

**Comment by sslattery** [comment]
OK so looks like we can just add cuda 8 to our image and then attach the container to the host card at runtime per the last post in http://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container

So I think we should add this to the container and verify we can run on the local card. Then we can work through configuration details for when a GPU is present (i.e. in the docker_cmake)

**Comment by sslattery** [comment]
we don't want the drivers however - just the toolkit to be installed

**Comment by aprokop** [comment]
Fixed in #180.
