### ISSUE TITLE
Docker for CUDA

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#198]
For some reasons, I couldn't compile `master` with the containers. I had to add `-D CMAKE_CXX_FLAGS="-std=c++11 --expt-extended-lambda"` to our script. This was inside the same image than the one we use on fetnat.

**Comment by sslattery** [comment]
Those flags are needed - they are not in the master script?

**Comment by dalg24** [comment]
@Rombur Do you want to open a PR to see the build on fetnat01?

**Comment by Rombur** [comment]
@sslattery they are not  in `CMAKE_CXX_FLAGS`, we've put them in `CUDA_NVCC_FLAGS`

**Comment by Rombur** [comment]
looks like it doesn't work on fetnat either

**Comment by Rombur** [comment]
Yes same error as the one I have `error: __host__ or __device__ annotation on lambda requires --expt-extended-lambda nvcc flag`

**Comment by dalg24** [comment]
> looks like it doesn't work on fetnat either

You tried "manually"?  How did the build go through before the merge...

**Comment by Rombur** [comment]
No, the PR fails.

**Comment by dalg24** [comment]
Oh sorry I had not seen it.  Hmmm would you do a commit with the new flags then?

**Comment by dalg24** [comment]
I start wondering if we want to remove the `-i` in the Jenkins [build script](https://github.com/ORNL-CEES/DataTransferKit/blob/master/docker/jenkins/build.sh#L36).
