### ISSUE TITLE
ETI: XXX_decl.hpp vs XXX.hpp

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#201]
Before the merge of #187, we use the combination `XXX_decl.hpp` (header) / `XXX_def.hpp` (definition) but now I only see `XXX.hpp` / `XXX_def.hpp` Why is that? I am confused how this work with [ETI](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Kokkos/src/DTK_ETI_SC_LO_GO_NT.tmpl)

**Comment by aprokop** [comment]
I did not notice that, and it also seems confusing to me now.

**Comment by sslattery** [comment]
Yes we should talk about this. A lot of what was added through the interface work is header-only for now. We should think about how ETI impacts this.

**Comment by dalg24** [comment]
Want to add a note about it on [ReadTheDocs](http://datatransferkit.readthedocs.io/en/latest/coding_guidelines.html)?

**Comment by sslattery** [comment]
Action item before close - add to [ReadTheDocs](http://datatransferkit.readthedocs.io/en/latest/coding_guidelines.html)

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
