### ISSUE TITLE
Update Docker container

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#208]
Catchall for the next Docker container update:

- [x] kokkos-tools ??
- [ ] ~~update CUDA (there is an update for CUDA 8.0)~~ this is irrelevant.  CUDA is installed when **extending** the DTK base image and the version needs to match whatever is installed on the host.

- [x] ninja-build
- [x] python-sphinx
- [x] python-breathe
- [x] kokkos-2.03.05

**Comment by aprokop** [comment]
Why is `kokkos-tools` not checked in?

**Comment by dalg24** [comment]
I just realized sphinx is not installed in the base image so we are not able to build the documentation from the container unless we run `apt-get update && apt-get install python-sphinx`.
We should probably add it next time we update the base image.

**Comment by Rombur** [comment]
We need to update Trilinos in docker to use Trilinos: 545269e1838282d98c4a113e17e6322d9c87fe8b or later.

**Comment by Rombur** [comment]
I spoke too soon. There has been another update that we need so we will need 4720e36b7892139f31589679b978c0049607de53 once it is merge into master (probably tomorrow).

**Comment by Rombur** [comment]
@dalg24 do you want me to update the image or do you want to do it?

**Comment by aprokop** [comment]
Do we close this?

**Comment by dalg24** [comment]
Feel free to re-open if you'd like something to be added to the base image.

**Comment by dalg24** [comment]
c.f. #382

**Comment by dalg24** [comment]
Any objection to updating clang-format to 6.0?  Speak now or forever hold your peace :/

**Comment by Rombur** [comment]
Can we use `IndentPPDirectives` and `IncludeBlocks` `Regroup` with clang-format 6.0?

**Comment by dalg24** [comment]
> Can we use IndentPPDirectives and IncludeBlocks Regroup with clang-format 6.0?

Please go ahead and push your changes to the .clang-format onto my branch

**Comment by dalg24** [comment]
> Can we use `IndentPPDirectives` and `IncludeBlocks` `Regroup` with clang-format 6.0?

I assume you meant `IndentPPDirectives` `AfterHash`.  Is that right?

**Comment by Rombur** [comment]
@dalg24 yes exactly.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
