### ISSUE TITLE
Improve queries

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#214]
We need to rework `spatial_query` and `nearest_query`. 
  - For `nearest_query`, we can allocate beforehand the size of the `indices` array/View (the size is the number of nearest neighbor we are looking for).
  - For `spatial_query`, the current implementation is not robust. We should do two passes. During the first pass, we count the number of leaf nodes which satisfy the predicate. We can then allocate an array/View that we fill during the second pass. During the first pass, we can also store the first node whose two children satisfy the predicate. This node can serve as `root` node for the second pass.

**Comment by aprokop** [comment]
The second pass in `spatial_query` should be optional. You could still provide some pre-existing number that you try to fill, and only do the second pass if you exceed it.

**Comment by aprokop** [comment]
Related to #217.

**Comment by dalg24** [comment]
Resolved by #221

**Comment by aprokop** [comment]
Is this really resolved? Should not we fix the knn search first to not do the count pass?

**Comment by Rombur** [comment]
no that's a performance issue. That's for next year.

**Comment by aprokop** [comment]
Can we record it somewhere, then?
