### ISSUE TITLE
Create Nearest Neighbor Point Cloud Map

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#217]
Tasks to complete this:

- [x] Wrap up loose ends on coarse local search

- [x] Finish ETI/directory structure refactor

- [x] Implement basic coarse global search without load balancing

- [x] Develop preliminary nearest neighbor transfer operator with Tpetra Import/Export or other communication strategy

**Comment by sslattery** [comment]
Let's create issues for each bullet

**Comment by aprokop** [comment]
This is a meta-ticket to track other tickets.
