### ISSUE TITLE
Code coverage uncertainty

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#228]
Few things:
1. Because we have a single OpenMP build, code coverage does not cover CUDA code.
2. For some reason, the `join` operator in `ExpandBoxWithBoxFunctor` is shown as *not* covered.

**Comment by sslattery** [comment]
Will take a look at coverage build for OMP_NUM_THREADS setting. Perhaps `join` is not getting called because only 1 thread is executing.

**Comment by sslattery** [comment]
So if I remember item 1 we decided was not a big deal. Have we determined what the issue with item 2 was?

**Comment by aprokop** [comment]
> So if I remember item 1 we decided was not a big deal. Have we determined what the issue with item 2 was?

No.

**Comment by Rombur** [comment]
I have the correct results [here](https://codecov.io/gh/ORNL-CEES/DataTransferKit/src/36a1632516a9560979b3772cc1ae40d8b7542469/packages/Search/src/details/DTK_DetailsAlgorithms.hpp#L122) The only difference is inside jenkins where the jobs are now separated instead of using a configuration matrix.

**Comment by dalg24** [comment]
This seem to be resolved by #313
