### ISSUE TITLE
DTK tutorial

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#231]
Once we have enough material, we could add a DTK tutorial to familiarize users for DTK.
We could write using jupyter+cling. A MueLu developer wrote [one](http://www.tawiesn.de/blog/?x=entry:entry170408-231332) for MueLu with an available Docker container that we could use as a starting point.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
