### ISSUE TITLE
ETI for CudaSpace

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#235]
Kokkos supports four "main" spaces: Serial, OpenMP, CudaUVM, and Cuda. However, our ETI, based on Tpetra, only instantiates three of those: Serial, OpenMP, and CudaUVM which means that we do _not_ support Cuda. In #234, there is a test that shouldn't pass on fetnat but it does because of UVM. Since we don't test Cuda space, it is very probable that it is broken/will be broken soon. So what should we do about it? We can add the ETI (however, we don't understand it very well...) or we can require UVM all the time. This would simplify the code but then we would have to closely monitor the performance. 

Personally, I think that we should rewrite the ETI and add support for Cuda. We depend too much on the ETI to not "own" it. It won't easy though :-(

relates to #224

**Comment by aprokop** [comment]
I remember at some point Tpetra *required* UVM. Is that still the case?

**Comment by Rombur** [comment]
Probably. They still say that it is required it the documentation of trilinos.org and since we have based our ETI on Tpetra's ETI, I don't think they test Cuda without UVM.

**Comment by aprokop** [comment]
Maybe look at `kokkos-kernels`?

**Comment by sslattery** [comment]
So if UVM is required for tpetra will we not also then require UVM due to our tpetra dependency?

**Comment by Rombur** [comment]
Yeah unless we don't use Tpetra for the global search we will need to require UVM all the time.

**Comment by sslattery** [comment]
So it seems we are restricted to UVM due to tpetra. Can this be closed?

**Comment by aprokop** [comment]
If we are indeed restricted to UVM, we need to prohibit instantiation of `DTK::View` on non-UVM memory spaces for CUDA.
