### ISSUE TITLE
xl compiler

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#236]
I quickly tried to install DTK on summitdev using the xl compiler. The first difference with `gcc` is that the variable `NVCC_WRAPPER_DEFAULT_COMPILER` needs to be set because by default the compiler is `g++`. The second difference is that it doesn't configure. I get an error about the mpicxx compiler not being able to compile a simple program. For some reason the flag `-+` is prepended to the `CMAKE_CXX_FLAGS`.

**Comment by aprokop** [comment]
`-+` is a valid option for xlC. Most likely, `nvcc_wrapper` is not smart enough to not pass this option to  cuda arguments. So, probably need to update the script.

**Comment by sslattery** [comment]
Can we make a kokkos github issue for this?

**Comment by Rombur** [comment]
I have open an issue here https://github.com/kokkos/kokkos/issues/897

**Comment by Rombur** [comment]
`XL` 13.x does not work with Kokkos but the next version of `XL` will.

**Comment by sslattery** [comment]
Need to verify that latest version of `XL` works on summit-dev

**Comment by Rombur** [comment]
I just checked and summitdev doesn't have xl 14 yet.

**Comment by Rombur** [comment]
So apparently `xl` 13.1.6 is the same as `xl` 14 :unamused: So we need to try again.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
