### ISSUE TITLE
Compliance to xSDK policies

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#237]
The xSDK draft community policies are available [here](https://xsdk.info/policies/).

As of draft version 0.3 (as of December 2016), these policies are:
- [x] M1. Each xSDK-compatible package must support either the standard GNU Autoconf or CMake
options
- [x] M2. Each xSDK-compatible package must provide a comprehensive test suite that can be run by
users and does not require the purchase of commercial software.
- [x] M3. Each xSDK-compatible package that utilizes MPI must restrict its MPI operations to MPI
communicators that are provided to it and not use directly MPI_COMM_WORLD.
- [x] M4. Each package team must do a “best effort” at portability to key architectures , including
standard Linux distributions, GNU, Clang, vendor compilers, and target machines 4 at ALCF, NERSC, OLCF.
- [x] M5. Each package team must provide a documented, reliable way to contact the development
team ; mode of contact may be by email or a website.
- [x] M6. Each package should respect the decisions made by other previously called packages
regarding system resources and settings.
- [x] M7. The package source code must come with an open source license , for example, one of the OSI listed licenses.
- [x] M8. Each package must provide a runtime API , for example a function call, to return the current
version number of the software.
- [x] M9. Each package should use a limited and well-defined symbol, macro, library, and include file
name space.
- [x] M10. It is mandatory that each package have an IDEAS accessible repository (not necessarily
publicly available), where the development version of the package is available. 
- [x] M11. No package should have hardwired print or I/O statements that cannot be turned off through a programmatic interface; output should never be hard-wired to stdout or stderr.
- [x] M12. If a package imports software that is externally developed and maintained, then it must allow
installing, building, and linking against an outside copy of that software.
- [x] M13 : When configured with a prefix a package must install its headers and libraries under
<install-prefix>/include/ and <install-prefix>/lib/, respectively.
- [x] M14: All xSDK-compatible packages must be buildable using 64 bit pointers (this is commonly the
default).
- [x] R1. It is recommended that each package have a public repository , for example at GitHub or
Bitbucket, where the development version of the package is available.
- [x] R2. It is recommend that all packages make it possible to run their test suite under valgrind in order to test for memory corruption issues.
- [ ] R3. It is recommended that each package adopt and document a consistent system for
propagating/returning error conditions/exceptions and provide an API for changing the behavior.
- [x] R4. It is recommended that each package free all system resources it has acquired as soon as
they are no longer needed.
- [ ] R5. It is recommended that each package provide a mechanism to export its ordered list of library
dependencies so that any other package or executable linking to the package knows to include these dependencies when linking.

@Rombur and I went quickly over version 0.3 and our understanding is that there is currently only one mandatory policy we do not satisfy:

> M8. provide a runtime API to return the package version number

**Comment by aprokop** [comment]
Could you please put a full list in this ticket and how we follow them?

**Comment by dalg24** [comment]
- [ ] create a list (assignee @aprokop)

**Comment by aprokop** [comment]
Not sure about what M6 means. M12 means that the old Nanoflann treatment is no go. R3 probably needs more work. Is R5 done through CMake export?

**Comment by aprokop** [comment]
M8 has been implemented in #238.

**Comment by dalg24** [comment]
FYI: xSDK now provides a template to document compatibility with the community policies.  See [xsdk-project/xsdk-policy-compatibility](https://github.com/xsdk-project/xsdk-policy-compatibility).

**Comment by aprokop** [comment]
DTK's compatibility was recorded at [xsdk-policy-compatibility](https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/dtk-policy-compatibility.md).
