### ISSUE TITLE
Add tolerancing/fuzzy math to coarse global search

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#24]
The bounding box computations in coarse global search have no tolerance so certain applications were failing to locate valid points where a shared interface is involved. A tolerancing scheme needs to be added to this algorithm. Tests should also be added.

**Comment by sslattery** [comment]
I have added the fuzzy math and tests to the coarse global search. It is not clear whether this fixes the bug that Damien observed by but it does add the correct floating point math that was missing from this search.

**Comment by dalg24** [comment]
It did fix the big.

**Comment by dalg24** [comment]
*bug
