### ISSUE TITLE
Implement the state machine underneath `Registry` and `UserApplication`

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#248]
One cannot do `get*` before setting the corresponding callback function in the Registry. However, one only needs to set only the functions used for a particular `get` to work.

At the minimum, we need to wrap the callback mechanism with a check that the corresponding function has been set.

**Comment by aprokop** [comment]
There is already a proper check in place that checks that the valid function exists. Invalid issue?

**Comment by aprokop** [comment]
I remembered: at the moment, we don't ever check whether DTK was initialized/finalized when working with `Registry`/`UserApplication`. We need to add checks to all of those methods.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
