### ISSUE TITLE
Document C/C++ interfaces

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#252]
We essentially need to triplicate the docs: C++, C, Fortran.

- Can we lift docs from C++ interface? Particularly, can we use doxygen to link to those chunks?
- Can we get statistics of the number of apps using C++/C/Fortran?

**Comment by sslattery** [comment]
Need corresponding domain model in ReadTheDocs (or Doxygen) as well for a high level overview of design and structure

**Comment by sslattery** [comment]
For now will just document c interface as it is closer to fortran than c++ and c++ users could use or read c

**Comment by aprokop** [comment]
Complete.
