### ISSUE TITLE
Supported configuration

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#259]
#258 shows two bugs that were not caught by our current test suite. So we need to think what we want to support. For now, the only optional dependency is MPI. Thus we only need to consider the `ExecutionSpace/compiler` combination. Below is a table of the possible combinations.

Compiler | S | O | C | SO | SC | OC | SOC
----------- | -- | -- | -- | ---- | --- | ---- | -------
clang 6.0 | - | - | - | X | - | - | ?
GCC 5.4  | - | - | - | X | ? | ? | X
GCC 7.1  | X | - | - | ? | - | - | -
Intel         | - | - | - | ? | - | - | - 
PGI (CE) | - | - | - | - | - | - | ?
XL (CE)   | - | - | - | - | - | - | ?

*Clang and Intel share the same OpenMP implementation. So we only need to test SO on one of them.
**Clang can compile CUDA code using CudaClang https://github.com/kokkos/kokkos/issues/941 (require the latest driver)
***XL (CE) is only available for Power architecture.
Legend:
 - S = serial
 - O = OpenMP
 - C = CUDA
 - SO = Serial + OpenMP
 - SC = Serial + CUDA
 - OC = OpenMP + CUDA
 - SOC = Serial + OpenMP + CUDA
 - ! = we should add this combination
 - ? = we may want to add this combination
 - `-` = we don't want this
 - CE = Community Edition

Compilers supported by Titan, Summit, and Cori

Compiler | Titan | Summit | Cori
----------- | ------- | ---------- | ------
clang      | X | X | X
GCC       | X | X | X
Intel        | X | - | X
PGI         | X | X |  - 
XL           | - | X | - 
Cray       | X | - | X

We may also add a configuration that does __not__ use MPI.

Feel free to edit the table!

**Comment by aprokop** [comment]
My 2 cents.

The compiler selection should be based on our target platforms (Titan, Summit, Cori).

Regarding the builds, I'd say
a) A single S, does not matter what compiler. This is just to catch the codepath. I don't expect this to be exercised much in the long term.
b) SO should be checked for all available compiler vendors using versions from target platforms. I think this is probably the most common variant in the near future
c) SOC should be checked to match the compilers on target platforms.

**Comment by Rombur** [comment]
> a) A single S, does not matter what compiler. This is just to catch the codepath. I don't expect this to be exercised much in the long term.

I disagree that this option will disappear in the future. I can fill an exascale system using only MPI with  multiscale codes. I expect that, if they can, a lot of people will keep their code MPI only.

**Comment by aprokop** [comment]
@dalg24 You can do that even if you compile with both Serial and OpenMP.

**Comment by Rombur** [comment]
@aprokop sure. I am just saying that I don't think that people will stop using S alone any time soon.

I have updated the first post, to add which compilers are/will be supported by each platform.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
