### ISSUE TITLE
Add example scripts to configure dtk

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#26]
Scripts that we use should be available.
We have to ensure we keep them up-to-date.
Also we should put here any script we use on eos or any other hpc facility.

**Comment by aprokop** [comment]
I think this is a good idea.

I would propose creating scripts/ dir in the dtk root, and populating it with scripts in the following format: 

 <machine_name>_<script_name>_cmake

The scripts should be executable (```chmod +x <script>```)

We can start with our workstation scripts. To make sure they are up to date, you link to them in your build directory. 
@sslattery If you have scripts for any HPC clusters, you should put them there too.

**Comment by sslattery** [comment]
Yes - I have some titan build scripts and Damien has done builds on Mira

**Comment by aprokop** [comment]
There are some scripts available now. Whenever we encounter most ssing script on a new platform, commit!
