### ISSUE TITLE
Kokkos Initialization

### ISSUE THREAD

**Issue by crtrott** [ORNL-CEES/DataTransferKit#273]
Hi

just a comment, after I was browsing through the code a bit I found a little thing: you say in the kokkos_init that Kokkos promises not to modify the arc/argv combo. That is not correct. We do remove all arguments Kokkos recognizes which start with '--kokkos' (e.g. we remove --kokkos-threads, but not --kokkos-shall-be-awesome ;-) ). 

You currently use std::forward to pass the stuff on. Not sure if this is an issue for you.

**Comment by dalg24** [comment]
@crtrott This was copied from Tpetra.  See [here](https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_Core.cpp#L83).  We did not bother checking that is was accurate.  Anyway, thank you for pointing that out!
