### ISSUE TITLE
Type Clashes in `DTK_Types.h`

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#287]
The code in [here](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Utils/src/DTK_Types.h) in `DTK_Types.h` creates typedefs such as `Coordinate` but this is not in a namespace because it is a C file. Should we add a DTK prefix to these so they are, for example, `DTK_Coordinate`?

**Comment by aprokop** [comment]
Yes, I think this would a correct approach to fix it. Then, in C++ interface we would still define them.

Should `DTK_Types.h` then be a `details/` file as it should only be included by DTK but not by users?

**Comment by sslattery** [comment]
I could see it being in a `details/` directory

**Comment by sslattery** [comment]
Although looking at these typedefs - do we need these at this point? Do we envision instantiations on other types for these variables?

**Comment by aprokop** [comment]
I would leave them in.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
