### ISSUE TITLE
Code style: input/output order 

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#295]
Right now, we don't have a rule on the order of inputs and outputs in functions. Sometimes we put the inputs first and then the outputs and sometimes it's the other way around. I think that it would make it easier to always use the same rule. What do you guys think? Personally, I prefer (output, input) over (input, output) because it makes more sense when you have a default parameter.

**Comment by sslattery** [comment]
I agree. I like  (output,input) because of the default parameter argument

**Comment by dalg24** [comment]
What if default param is output?

**Comment by sslattery** [comment]
what is an example of an output argument having a default parameter?

**Comment by dalg24** [comment]
[`DistributedSearchTreeImpl::sortResults()`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Search/src/details/DTK_DetailsDistributedSearchTreeImpl.hpp#L105)
[`DistributedSearchTreeImpl:: communicateResultsBack()`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Search/src/details/DTK_DetailsDistributedSearchTreeImpl.hpp#L93)
[`DistributedSearchTreeImpl:: queryDispatch()`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Search/src/details/DTK_DetailsDistributedSearchTreeImpl.hpp#L69)

**Comment by aprokop** [comment]
A tangential comment: https://stackoverflow.com/questions/26441220/googles-style-guide-about-input-output-parameters-as-pointers.

**Comment by Rombur** [comment]
We have default output parameter because you "packed" the input parameter (compute_distance) with the output parameter.

**Comment by Rombur** [comment]
Apparently, google uses (input, output) but they also disallow default parameters
https://stackoverflow.com/questions/27934633/google-c-style-guide-why-input-then-output-parameter-ordering

**Comment by sslattery** [comment]
I will admit that if default parameters are not allowed then I actually prefer (input,output)

**Comment by dalg24** [comment]
google is not going to tell us how to live or lives.  Or is it?

**Comment by Rombur** [comment]
Here what cpp guideline recommends https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-out-multi Apparently `tie` avoids the extra copy. 

At the end of the day, I don't think that there is a perfect choice but I would like us to pick one to improve readability.

**Comment by Rombur** [comment]
@aprokop I am sure you have an opinion on this

**Comment by aprokop** [comment]
@Rombur I do: you should stop bikeshedding...
