### ISSUE TITLE
Switch to clang-format 5.0  

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#302]
We should update clang-format 5.0 if only for the `ReflownComments` option: `Comment reflow support added. Overly long comment lines will now be reflown with the rest of the paragraph instead of just broken. Option ReflowComments added and enabled by default.` Right now, when the comment is too long, clang-format breaks the comment but sometimes create sth like this:
```c++
// Such a great comment! I
// know.
// This is unbelievable!
```

**Comment by aprokop** [comment]
Sure, why not. Just need to add llvm-5 to Spack.

**Comment by dalg24** [comment]
-1 for Spack

We are using the LLVM PPA in our Dockerfile.  See [here](https://github.com/ORNL-CEES/DataTransferKit/blob/master/docker/Dockerfile_stack#L34-L40).

**Comment by dalg24** [comment]
Regardless, Bruno correctly flagged this as Low Priority.  This is something we want to do eventually but we should not waste any time on it for now and focus on meeting our milestones ;)
