### ISSUE TITLE
CUDA 9.0 compile errors

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#308]
See build [513](https://cloud.cees.ornl.gov/jenkins-ci/job/DataTransferKit-experimental/513/compiler=GCC54,slave=fetnat01/console) on Jenkins.
Intrepid2 seems to be causing them.

**Comment by Rombur** [comment]
CUDA 9.0 is not yet supported by Kokkos https://github.com/kokkos/kokkos/issues/1174

**Comment by sslattery** [comment]
Compilation now works but on some systems there are failing tests. Will try to run `valgrind` next on serial versions of failing tests to see if there are some uninitialized data warnings or other read/write errors which would behave differently using CUDA.

**Comment by Rombur** [comment]
Fixed by #472
