### ISSUE TITLE
L2 Projection Prerequisites

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#319]
The following tasks should be completed before development of an L2 projection operator:

- [ ] Define inputs and problem generator for mesh problems

- [ ] Obtain example problem from NEAMS users for development of interface and tests

- [ ] Decide on interface to FEM-based operators

- [ ] Update #303 to use interface and merge

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
