### ISSUE TITLE
Latest from MOOSE/Libmesh breaks DTK build

### ISSUE THREAD

**Issue by amccaskey** [ORNL-CEES/DataTransferKit#32]
Building DTK using the Libmesh install produced by the MOOSE update_and_rebuild_libmesh.sh script causes the following build error: 

DTK_LibmeshEntityIntegrationRule.cpp: In member function ‘virtual void DataTransferKit::LibmeshEntityIntegrationRule::getIntegrationRule(const DataTransferKit::Entity&, int, Teuchos::Array<Teuchos::Array<double> >&, Teuchos::Array<double>&) const’:
DTK_LibmeshEntityIntegrationRule.cpp:65:46: error: conversion from ‘libMesh::UniquePtr<libMesh::QBase> {aka std::unique_ptr<libMesh::QBase, std::default_delete<libMesh::QBase> >}’ to non-scalar type ‘libMesh::AutoPtr<libMesh::QBase>’ requested
           static_cast<libMesh::Order>(order) );

This must be caused by recent addition of the --enable-unique-ptr flag to that build script. Switching it to --disable-unique-ptr fixes the build issue. 

Not sure if the fix should just be on the user to switch this flag, just wanted to raise the issue here.

**Comment by sslattery** [comment]
I didn't know there was such a flag in the build. Looking at include/quadrature.h the build API only returns an AutoPtr<QBase> object. Is --enable-unique-ptr the default in the MOOSE build?

**Comment by amccaskey** [comment]
Yea it's now the default in the script that pulls down and builds libmesh https://github.com/idaholab/moose/blob/devel/scripts/update_and_rebuild_libmesh.sh. They just recently added this, it wasn't there when we were doing all this DTK work before. 

A quick look at the configure help says that this flag tells libmesh to "use a true unique_ptr implementation instead of libMesh AutoPtr"

**Comment by sslattery** [comment]
Is there some typdef in a file that we need to include now? The quadrature API returns an AutoPtr so its not clear why it is returning a unique ptr.

**Comment by sslattery** [comment]
Never mind. The quadrature api was changed. I will update and push.

**Comment by sslattery** [comment]
Just did a push. Let me know if it works.

**Comment by amccaskey** [comment]
That works. Thanks!
