### ISSUE TITLE
PGI 17.10

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#323]
PGI 17.10 was released yesterday. It is supported by Kokkos so we should make it work too.

**Comment by Rombur** [comment]
With pgi 17.10, we get a `static_assert` from Kokkos on top of the  linking problems :disappointed:

**Comment by sslattery** [comment]
should we alert the Kokkos teams to any of these issues?

**Comment by Rombur** [comment]
Yes but I want to write a test that show the problem first.

**Comment by Rombur** [comment]
Closing this since PGI 18.4 is out. PGI 18.4 has an `llvm` back end so it should be easier to make it work.
