### ISSUE TITLE
Search Tree Performance Assessment

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#332]
Below are some preliminary results.  I pushed the code I used to [dalg24:performance_assessment](https://github.com/dalg24/DataTransferKit/tree/performance_assessment).

Note that I have been using `OMP_NUM_THREADS` to control the number of threads which might not be adequate.  @aprokop suggested I look at `OMP_PROC_BIND`, `OMP_PLACES`, and such. 

# Vary number of OpenMP threads
* 1M random points in unit cube
* 100k queries

|                          | build |        | knn search |        | radius search |        |
| ------------------------ | ----- | ------ | ---------- | ------ | ------------- | ------ |
| boost rtree              | .267s | (0.79) | 3.05s      | (0.37) | .148s         | (0.33) |
| nanoflann kdtree         | .376s | (1.12) | 4.46s      | (0.55) | .168s         | (0.38) |
| dtk bvh (serial)         | .337s | (1.00) | 8.13s      | (1.00) | .448s         | (1.00) |
| dtk bvh (omp 2 threads)  | .197s | (0.58) | 4.14s      | (0.51) | .264s         | (0.59) |
| dtk bvh (omp 4 threads)  | .115s | (0.34) | 2.31s      | (0.28) | .164s         | (0.37) |
| dtk bvh (omp 8 threads)  | .088s | (0.26) | 1.31s      | (0.16) | .097s         | (0.22) |
| dtk bvh (omp 16 threads) | .055s | (0.16) | 0.80s      | (0.10) | .072s         | (0.16) |
| dtk bvh (cuda)           | .045s | (0.13) | 4.51s      | (0.55) | .014s         | (0.03) |

# Vary problem size
* dtk openmp 4 threads
* 100k queries

|                    |        | build  |           |       | knn   |           |        | radius |           |
| ------------------ | -------| ------ | --------- | ----- | ----- | --------- | ------ | ------ | --------- |
|                    | dtk    | boost  | nanoflann | dtk   | boost | nanoflann | dtk    | boost  | nanoflann |
| 1k                 | .707ms | .344ms | .338ms    | 1.06s | 1.87s | 2.11s     | 31.8ms | 24.0ms | 19.1ms    |
| 10k                | 2.25ms | 3.61ms | 3.70ms    | 1.48s | 2.42s | 2.99s     | 48.1ms | 39.4ms | 32.4ms    |
| 100k               | 19.1ms | 41.7ms | 39.5ms    | 1.72s | 2.69s | 3.52s     | 80.8ms | 68.0ms | 62.0ms    |
| 1M                 | 124.ms | 300.ms | 450.ms    | 2.36s | 3.06s | 4.88s     | .176s  | .163s  | .195s     |

**Comment by hydroo** [comment]
During the last couple of days, I analyzed the performance of Search/examples/bvh_driver on Summitdev.

[bvh_1.xlsx](https://github.com/ORNL-CEES/DataTransferKit/files/2005710/bvh_1.xlsx)

Charts are to the right of the data.

Mind that:
- This was done before #390, which improves the speed of construction by ~9% (serial) on CPU.
- Summitdev is a Testbed, i.e. the result might be 100% what happens on Intel hardware.

I mainly talked to @dalg24 about it.
Let me know if you have questions.

**Comment by dalg24** [comment]
Keep track PRs related to search performance here:

PR | Description | Status
--- | --- | ---
390 | builtin function to count leading zeros | merged
393 | heap in priority queue | ready to merge?
394 | avoid square root if possible when computing distance | in progress

**Comment by aprokop** [comment]
@dalg24 Can this be simply closed, or do you want to move the table to ArborX?
