### ISSUE TITLE
Develop Hybrid Transport Demonstration

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#335]
A demonstration for solution transfer in a coupled deterministic/stochastic transport simulation will be developed. This is a high level issue for managing the work. 

**Notes from initial meeting**

Integrated test problems:
- reactor vessel fluence calculation
- simple problem - dog leg mock-up

Parallelism:
- total number of domains is fixed (number of MPI ranks are fixed)
- shift decomposes ranks into groups of sets and blocks -> sets * blocks =
   ranks
- denovo decomposition is in i and j (not physically in k)
- will build map and transfer after denovo has run

Improvements for the future:
- currently restricted that the number of shift and denovo ranks are the same
- would like to have arbitrary ranks between codes

Problem setup:
- R_S = # of shift ranks
- R_D = # of denovo ranks
- R_S / R_D will vary from 1 to 1000

Discretization:
- cell integrated data
- cell data is a function of energy groups
- meshes are conformal
- would still want an interpolation capability so they can have different
   grids to help with memory constraints

Transfer operators:
- MLS most attractive
- FEM interpolation with evaluate function and with FEM bases

Next steps:
- Bruno to get RSICC license
- Develop a problem generator using Denovo/Shift mesh creation and
   partitioners
- Denovo mesh and partitioner is in Profugus

**Comment by sslattery** [comment]
The following is the work plan:

#368 Implements the baseline partitioners for each of the two different problem classes:

- [x] `CartesianMesh` class which contains the base mesh description need by both deterministic and stochastic grids. This also contains convenience functions for generating the needed `Kokkos::View` data structures.

- [x] `DeterministicMesh` class which builds a `CartesianMesh` using the partitioner derived from the deterministic application.

- [x] `MonteCarloMesh` class which builds a `CartesianMesh` using the partitioner derived from the Monte Carlo application.

A new PR will take these implementations and implement the problem generator interface which will read XML inputs from the actual Exnihilo code base:

- [ ] An implementation of the `PointCloudProblemGenerator` interface.

- [ ] A driver/example using Exnihilo inputs from which to build scaling and performance studies.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
