### ISSUE TITLE
Template NearestNeighborOperator on General View Properties

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#337]
The current `NearestNeighborOperator` has the following class signature:

```
template<class Device>
class NearestNeighborOperator;
```

To allow for more general views with different layout and device combinations we would like to template on general view parameters:

```
template<class... ViewProperties>
class NearestNeighborOperator;

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
