### ISSUE TITLE
REGION_NAME() macro should be prefixed

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#347]
We use it to mark parallel regions in parallel dispatch operations (e.g., `Kokkos::parallel_for()`).

Here are a few changes I would like to suggest:
* Prefix with `DTK_`
* Rename the macro, possibly to `DTK_MARK_REGION()`
* Move to a different header, possibly a new `DTK_Macros.hpp` file.  IMO, `DTK_ConfigDefs.hpp` is not a good fit.

Any comment on this?

**Comment by aprokop** [comment]
My 2 cents:
1. `REGION_NAME` should definitely be renamed, I believe it's included in the header files that are installed, so it is in the global space and therefore does not adhere to xSDK policies.
2. I am not sure we need to prefix the boost version, as if I recall correctly `CURRENT_FUNCTION` would include a namespace, and therefore it's going to be DTK specific.
3. I have no opinion on moving it to a different file.

**Comment by dalg24** [comment]
@aprokop By prefix I mean the name of the macro not the label.

**Comment by aprokop** [comment]
@dalg24 I stand by my comment, the macro should be prefixed unless you guarantee that it's not exposed to a user.

**Comment by dalg24** [comment]
I AGREE WITH YOU

**Comment by sslattery** [comment]
I like the name `DTK_MARK_REGION` and I support moving it and other similar macros not defined at configure time to a file such as `DTK_Macros.hpp`
