### ISSUE TITLE
Properties on tests are set incorrectly when enabling OpenMP

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#375]
When adding a test with TriBITS/CMake we have not been setting test properties carefully.
We might want to look into passing `NUM_TOTAL_CORES_USED` and `ENVIRONMENT OMP_NUM_THREADS=<N>` to `TRIBITS_ADD_EXECUTABLE_AND_TEST()`.  We might also consider `RUN_SERIAL` in some cases.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
