### ISSUE TITLE
Clang-tidy

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#379]
Starting from CMake 3.6, CMake has built-in support for clang-tidy. This means that clang-tidy can be used by simply adding sth like: `-DCMAKE_CXX_CLANG_TIDY="/usr/bin/clang-tidy-5.0;-checks=performance-*,mpi-*,portability-*,readability-*"` during configuration. Right now, we are using CMake 3.5 in Docker so we will need to update CMake. The list of acceptable flags for clang-tidy is [here](http://clang.llvm.org/extra/clang-tidy/#using-clang-tidy).

**Comment by dalg24** [comment]
I wonder if we can use `.clang-tidy` configuration file with this.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
