### ISSUE TITLE
Refactor RBF interface to use radius at evaluation instead of construction

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#38]
RBF interface currently has RadialBasisPolicy::create( radius ) and RadialBasisPolicy::evaluateValue( basis, dist ). We want this to be RadialBasisPolicy::create() and RadialBasisPolicy::evaluateValue( basis, dist, radius ).

- [x] Refactor RadialBasisPolicy interface to pass the radius as an evaluation argument

- [x] Update basis function implementations and tstRadialBasis.cpp so tests pass

- [x] Propagate basis function interface changes through point cloud operators. Use the radius from the parameter list for now

- [x] Ensure all point cloud operator test pass

**Comment by sslattery** [comment]
Per the work in pull request #52 this is complete if all tests in that pull request pass. Passing to Damien to review.

**Comment by dalg24** [comment]
@sslattery: Can we close this issue?
