### ISSUE TITLE
Linking Interface Data Structures to Mesh-Free Operators

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#389]
We will need an interface to couple interface data structures (i.e. the [`NodeList`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Interface/src/DTK_NodeList.hpp)) to operator input (i.e. the [`NearestNeighborOperator`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Meshfree/src/DTK_NearestNeighborOperator_decl.hpp)). This is needed, for example, to support the development of the hybrid transport benchmark (#335).

An example of such an interface can be found [here](https://github.com/dalg24/DataTransferKit/blob/554069de64f8b0441a540d38d41f903a1822e107/packages/Meshfree/src/DTK_PointCloudOperator.hpp)

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
