### ISSUE TITLE
C Interface to Point Cloud Operators

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#39]
Develop C/Fortran interfaces to the point cloud operators for future Fortran interface.

- [x] Define Fortran/C compilers and systems to be used for the work

- [x] Define algorithm input options

- [x] Define algorithm input and output data

- [x] Design C interface using input and output parameters

- [x] Design Fortran interface to interoperate with C interface

- [ ] Review Fortran interface with ANL/LLNL code teams

- [x] Implement point cloud operators under C interface

- [x] Test C interface to operators

- [x] Implement the C interface under the Fortran interface

- [x] Test the Fortran interface to operators

**Comment by sslattery** [comment]
Any progress here?

**Comment by dalg24** [comment]
cf PR #56

**Comment by dalg24** [comment]
an PR #57

**Comment by sslattery** [comment]
we haven't reviewed this with the users yet but this is effectively done. should we close?

**Comment by dalg24** [comment]
Sure
