### ISSUE TITLE
Explicit Template Instantiations

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#4]
Provide a *_inst.cpp file with explicit instantiations for all DTK templates types that have a common set of typical template parameters. Do the same for Tpetra objects. This should dramatically reduce compile times.

So far, completed for: PointCloud/src/ -> `EuclideanDistance<int DIM>`

Add completed classes as we progress...

**Comment by sslattery** [comment]
Remove all template types in classic unit tests that don't match internal types.

**Comment by sslattery** [comment]
We should have an ETI configure option that automatically turns on the right Tpetra instantiations. Several people have emailed with build errors regarding this.

Also need to revisit point cloud operator ETI.

**Comment by sslattery** [comment]
Looking at this first for point cloud operators as part of speeding up builds. Here is the first time on my laptop on 4 corse for building just DTK with the classic adapters (no other mesh adapters): 9m13.835s

Will report times after ETI added to point cloud operators

**Comment by sslattery** [comment]
Added ETI for a lot of point cloud and build times increased a bunch: 15m3.224s

What happened?

**Comment by dalg24** [comment]
weird

**Comment by Rombur** [comment]
Is it possible that you instantiate too many templates? Maybe you are instantiating templates that were not created before.  Something else that you can do if one file takes a lot longer than the others is to split the instantiations so that several processors can work on it at the same time.

**Comment by rppawlo** [comment]
Did you remember to hide the definitions when ETI is enabled (except for the .cpp file)? Otherwise you are just adding more builds of the same object. That's the only way I could see the times increasing with ETI.

**Comment by sslattery** [comment]
I did include the definitions in the CMake header list. Could this be the issue then?

**Comment by sslattery** [comment]
OK tried turning off more of the ETI and am getting this:

`/Users/uy7/software/Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:168:4: error: "Tpetra: No global ordinal types in the set {int, long long, long, unsigned long, unsigned} have been enabled."
#  error "Tpetra: No global ordinal types in the set {int, long long, long, unsigned long, unsigned} have been enabled."`

However, we have unsigned long explicitly set...

**Comment by Rombur** [comment]
There is something weird with global ordinal and unsigned / unsigned long Try again with long long and see if it works

**Comment by sslattery** [comment]
I let it turn on LO=int and GO=int on its own. I'm sure that will work and this is just a bug in their default types from that Tpetra_ConfigDefs message. This should have been caught at configuration.

**Comment by sslattery** [comment]
Looking at Tpetra_ConfigDefs.hpp:164 I don't think that macro is getting set without input from the user configure

**Comment by sslattery** [comment]
Pull request #48 added ETI to the point cloud operators. We are planning future work for templating the code further and using ETI to manage that. Therefore I think we are done for now but we should review. Going to assign to @dalg24  for the review.
