### ISSUE TITLE
Handle units conversion

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#41]
will elaborate on this later

**Comment by Rombur** [comment]
Add a way to project a solution from xyz to rz.

**Comment by rppawlo** [comment]
Some codes use 2D r-z, others use 3D r-t-z and others use 3D r-z-t. I would be nice to support all these options.

**Comment by sslattery** [comment]
Any more discussion on this? If this is something that people think should be in the new version of the API we can do that. I could see that as basically functors someone would pass to a `for_each` and apply to a `kokkos::view`

**Comment by Rombur** [comment]
I think this would be pretty nice to have but it's definitely not on top of the list of things that need to be done.

**Comment by aprokop** [comment]
Is this still relevant, or could we close it?
