### ISSUE TITLE
C Interface Refactor

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#420]
For the most part our design of the C interface turned out pretty well as preliminary code integrations were successful and clean. For the most part,  I like the idea of having a single interface, namely the C interface, through which users interact with the code. A few things were observed resulting in some upcoming changes:

1. Removing `DTK_ParallelTraits.hpp`. The work in #408 substantially reduced the amount of code in this header file and the remaining bits can be moved to another more logical location.
2. Eliminating the `DataTransferKit::View` class. For the most part this was an intermediary designed to hide kokkos from users of the C++ interface. If we are just going to have a primary C interface for transfer operators we don't really need this additional layer of code. 
3. Reordering the `DTK_C_API.h`. The content is good here I just think it needs a bit more logical ordering.
4. Considering renaming `DTK_C_API.h` to `DTK.h`. It would be nice if users could just include that single header and user DTK.
5. Decide on where to locate the Map C interface implementation. Currently this sits at the end of the packages list. However, it would be nice to maybe just have this in the main interfaces package and have different operators implement some kind of static builder interface to register their factory with the main map builder. This change/design process may be substantial enough to warrant it's own PR.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
