### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#421]
Our current build structure has `DataTransferKit` as a package and our remaining capabilities as sub packages. However, all of our packages sans a few (e.g. benchmarks) are required. Having a multitude of different packages creates some negative side effects. For example, we have a replicated ETI system in every package. My idea is:

1. Reduce the number of required packages to a single required `core` package but use subdirectories in the `src` directory to manage the implementation.
2. Optional packages may remain their own packages. This will allow us to easily turn them on and off. In addition, optional packages (such as benchmarks) will likely not have ETI anyway.
3. Consider making search its own package (e.g. split it from DTK) and host it in a separate repo. We would then snapshot search into DTK or allow users to link to their own version (to follow xSDK rules).
4. We may have a distributor-like MPI infrastructure we write to replace Tpetra that is also in its own package or is part of the search package.

**Comment by aprokop** [comment]
Why not make it a single package, and then control what builds by tracking what's enabled? (and this has nothing to do with directory organization).

+1 for making search its own package. The MPI/Distributor infrastructure should be a part of the search package.

**Comment by sslattery** [comment]
resolved by #476
