### ISSUE TITLE
Add performance regression testing

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#429]
Now that we have spent a lot of time optimizing the search, we should monitor the performance to make sure that a future commit does not slow downs the code.

**Comment by aprokop** [comment]
Any idea how to do that? I know one can use CMake to track some metrics, but not sure if that's what we want to do. We could take a look at how Kokkos does things, I think they have gold files and allow 5% deviation.

**Comment by dalg24** [comment]
Benchmark is still running and logging time measurements but it won't make the Jenkins build fail anymore as of #507.  The check is just not reliable enough and prevent us from merging code.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
