### ISSUE TITLE
Missing test files in Meshfree tests

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#434]
Two exo files are missing: `coarse_sphere.exo` and `fine_sphere.exo`. This leads to build failure. I'm not sure why this hasn't been noticed before. It only matters when NetCDF is enabled.

**Comment by dalg24** [comment]
These have been added in 4965472.  Most likely we are doing something wrong in CMake (i.e. should disable tests that use them and not trying to copy them into the build dir if DTKData is not detected.

**Comment by aprokop** [comment]
Yes, we should check for the presence of data submodule. I don't have it checked out.
