### ISSUE TITLE
Remove boost dependency

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#447]
We should remove the unnecessary boost dependency for the release:
 - boost.mpi
 - boost.serialization

**Comment by dalg24** [comment]
You mean remove boost dependency altogether or dependency on compiled boost.MPI and boost.serialization?

**Comment by Rombur** [comment]
just boost.mpi and boost serialization

**Comment by dalg24** [comment]
Fixed by #449
