### ISSUE TITLE
Update Fortran interface for DTK_createMap with options string arg

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#465]
#456 broke Fortran interface without CI build failing.  Need Fortran tests for map create/apply.

**Comment by aprokop** [comment]
Note: this will most likely require some test refactoring in `MapFactory/tests` similar to how things done in `Interface/tests`.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
