### ISSUE TITLE
Create general missed range DOF capability and keep missed range data

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#50]
Currently only the consistent interpolation operator can keep missed range DOFS where DTK will put zeros in the solution vector. We have added capability to that map to keep the original solution. We need to propagate this capability and tracking missed range DOFS to all maps. This should be straightforward as this is handled entirely by the parallel search.

**Comment by dalg24** [comment]
PR #51 is dealing with this issue.

**Comment by sslattery** [comment]
Not entirely - we need to generalize to all operators

**Comment by sslattery** [comment]
Fixed in PR #51
