### ISSUE TITLE
Add Kokkos profiling regions to BVH

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#533]
Kokkos has [profiling regions](https://github.com/kokkos/kokkos-tools/wiki/Profiling-Hooks) that can be stacked. I propose adding the following regions:
- A region encompassing full BVH construction
  Is placed inside the constructor
- Regions encompassing each stage of BVH construction
  While some of the stages consist of a single parallel directive, some (like sorting) do not. 
- A regions encompassing full BVH traversal
  Both kNN and spatial (**edit** meaning `BVH::query()` specializations)
- Regions encompassing specific stages of the batched queries (e.g. sorting, 1st pass and 2nd, reordering, truncating, etc.)

This approach would allow to know in a standard manner:
- Developers: The proportion each stage of construction take
- Applications: The time taken by BVH construction and search

In the immediate future, the stage regions should allow us to produce interesting data for the paper.

**Comment by sslattery** [comment]
Do they have their own profiling backends that implement the hooks or are there implementations for standard profilers?

**Comment by aprokop** [comment]
Both. They have simple timer outputs, and one can plug in VTune and others.

**Comment by aprokop** [comment]
Closing as it moved to arborx/arborx#11
