### ISSUE TITLE
Refactor Map Operator Factory

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#55]
The map operator factory scheme is not scalable as more operators are added - it becomes very hard to maintain. In addition, it does not follow the open-closed principle as users can not inject their own implementations into the factory. We need to assess our construction scheme and use an abstract builder/factory pattern.

**Comment by dalg24** [comment]
also invalid parameter list will not throw but will return a null ptr. is that really what we want?

**Comment by sslattery** [comment]
Enhancement for version 2 so will not fix.
