### ISSUE TITLE
Installing DTK with Libmesh Adapters

### ISSUE THREAD

**Issue by PeterK26** [ORNL-CEES/DataTransferKit#556]
I'm trying to install DTK on a local machine running Ubuntu. Configuration is successful and installation proceeds normally until reaching the Libmesh adapters. Despite having already installed and tested Libmesh, it looks like some of its source files cause an error. The errors I get from make are:

> .../include/libmesh/auto_ptr.h:39:34: error: ‘make_unique’ is not a member of ‘std’
 #define libmesh_make_unique std::make_unique

> .../include/libmesh/standard_type.h:222:6: error: expected primary-expression before ‘>’ token
      >(&std::get<sizeof...(Types)-n_minus_i>(example)));
This type of error occurs in multiple files

> DataTransferKit/packages/Adapters/Libmesh/src/CMakeFiles/dtk_libmeshadapters.dir/build.make:62: recipe for target 'DataTransferKit/packages/Adapters/Libmesh/src/CMakeFiles/dtk_libmeshadapters.dir/DTK_LibmeshAdjacencies.cpp.o' failed
make[2]: *** [DataTransferKit/packages/Adapters/Libmesh/src/CMakeFiles/dtk_libmeshadapters.dir/DTK_LibmeshAdjacencies.cpp.o] Error 1
CMakeFiles/Makefile2:9596: recipe for target 'DataTransferKit/packages/Adapters/Libmesh/src/CMakeFiles/dtk_libmeshadapters.dir/all' failed
make[1]: *** [DataTransferKit/packages/Adapters/Libmesh/src/CMakeFiles/dtk_libmeshadapters.dir/all] Error 2

The Libmesh related cmake options I'm using are:

`Libmesh_LIBRARY_DIRS:PATH={path to lib directory}`
 `Libmesh_INCLUDE_DIRS:PATH={path to include directory}` 
 `TPL_ENABLE_Libmesh:BOOL=ON` 
 `Trilinos_ENABLE_DataTransferKitLibmeshAdapters:BOOL=ON`

As far as I can tell, there's nothing wrong with the flagged files especially since Libmesh installed successfully. Are there any known issues like this for installing DTK with Libmesh? If I turn off Libmesh adapters, then DTK is able to install and pass all tests (except check_no_trailing_whitespaces_or_tabs due to timeout). I want to use DTK for solution transfer between Exodus II meshes, so I assume I need to build with Libmesh (or maybe one of the other mesh adapters).

**Comment by dalg24** [comment]
Try to configure with `-D Trilinos_CXX11_FLAGS="-std=c++14"`

**Comment by PeterK26** [comment]
Should I still be using `-D Trilinos_ENABLE_CXX11:BOOL=ON` as suggested in the installation page? Or is the a CXX14 version?

**Comment by dalg24** [comment]
`std::make_unique_ptr` is only available since C++14.
What version of Trilinos are you using?  `CXX11` has been the default for a while now.

**Comment by PeterK26** [comment]
I'm using version 12.13. I was using that command since it's given in the example configure script from [the installation instructions](http://ornl-cees.github.io/DataTransferKit/about/)

**Comment by PeterK26** [comment]
I added `-D Trilinos_CXX11_FLAGS="-std=c++14"` to my configure options and it looks like it changed the flag to c++14. Now I'm trying to install

**Comment by sslattery** [comment]
Is the inclusion of `std::make_unique` a recent addition in LibMesh? It would seem the updated that in a recent release.

**Comment by PeterK26** [comment]
I'm not sure how recent it is. The way `std::make_unique` is implemented is supposed to be c++11 compatible. What LibMesh version was DTK designed to work with?

**Comment by Rombur** [comment]
> The way std::make_unique is implemented is supposed to be c++11 compatible.

They may check if your compiler supports c++14, if it does they use `std::make_unique` otherwise they fall back to a different implementation. In that case you will get an error if you don't compile **all** your codes with c++14.

**Comment by sslattery** [comment]
yeah that could be it. looking at the offending header this somehow must get activated:

```

**Comment by PeterK26** [comment]
Since adding the c++14 flag, I reach about the same point in installation, but with a different error.

> .../DataTransferKit/packages/Adapters/Libmesh/src/DTK_LibmeshEntityIntegrationRule.hpp:70:66: error: ‘QGAUSS’ is not a member of ‘libMesh’
         const libMesh::QuadratureType quadrature_type = libMesh::QGAUSS );

**Comment by dalg24** [comment]
Replace https://github.com/ORNL-CEES/DataTransferKit/blob/c3d58bc40b69626d9c68bb338daf59c147eaa44a/packages/Adapters/Libmesh/src/DTK_LibmeshEntityIntegrationRule.hpp#L51
with `#include <libmesh/quadrature_gauss.h>`

**Comment by Rombur** [comment]
I guess they changed their interface. Maybe try an older version of Libmesh

**Comment by dalg24** [comment]
Or downgrade libmesh to v1.0.0

**Comment by PeterK26** [comment]
Thanks, if I get more errors then I'll downgrade

**Comment by sslattery** [comment]
Not so sure: https://github.com/libMesh/libmesh/blob/8d1614a800e277d0f65fb4739d0cb73b0d19bc66/src/quadrature/quadrature_build.C#L71

**Comment by sslattery** [comment]
it would seem it is supported still

**Comment by sslattery** [comment]
note though that the enumeration style has changed slightly: https://github.com/libMesh/libmesh/blob/master/include/enums/enum_quadrature_type.h

Could this be an issue?

**Comment by sslattery** [comment]
So after further analysis it looks like they have changed how their enumerations are included. Because they are now forward declared the assumption that we would get them included by including the quadrature header is no longer valid. 

Our suggestion is to either try disabling `LIBMESH_FORWARD_DECLARE_ENUMS` (see https://github.com/libMesh/libmesh/blob/c36b43fe845698e39e3810292843483069863977/include/quadrature/quadrature.h#L31 for how they use this now) which will remove the forward declaration or to roll back to libMesh 1.0.0

**Comment by PeterK26** [comment]
Ok, thanks for the suggestions. If version 1.0.0 is known to work with DTK, then I'll just try installing with that
