### ISSUE TITLE
Are there any basic DTK example problems?

### ISSUE THREAD

**Issue by PeterK26** [ORNL-CEES/DataTransferKit#557]
I have DTK2.0 installed any it passes its self checks, but I'm still not too sure how to start running my own problems. I've looked at the docs for the C API, but a sample problem would be a lot more helpful. Are there any basic examples included anywhere in the installation? 

So far I've used DTK through libMesh (there's a [solution transfer example](https://github.com/libMesh/libmesh/blob/master/examples/solution_transfer/solution_transfer_ex1/main.C) using DTK), but the solution changes when it's transferred to the target mesh (as far as I know, the actual solution transfer part is done with DTK). Since this example is behaving strangely, having another simple example would be useful. I'm interested in solution transfer between Exodus II meshes like in libMesh's DTK example.   

![image](https://user-images.githubusercontent.com/48396192/58375425-c5757100-7f20-11e9-9514-47b844575c0a.png)

**Comment by sslattery** [comment]
This is the best example for using libmesh: https://github.com/ORNL-CEES/DataTransferKit/blob/dtk-2.0/packages/Adapters/Libmesh/example/tstMoabtoLibmeshParallelTransfer.cpp 

Note that the target mesh in this case is libmesh while the source mesh uses Moab. You can use the target libmesh code as an example of how to replace the source mesh code with libmesh. The internal libmesh example you pointed to uses an even older legacy version of DTK than 2.0 and if I remember they had pinned themselves to a specific repo hash of DTK for their work so I am not surprised that the internal example is not functioning correctly.

**Comment by PeterK26** [comment]
Thanks, that example looks very helpful.
