### ISSUE TITLE
Using mesh-to-geometry integral assembly mapping

### ISSUE THREAD

**Issue by PeterK26** [ORNL-CEES/DataTransferKit#559]
I'm trying to integrate my source mesh within the domains defined by the target mesh elements (the target mesh is coarser) and map the integrated solutions to the target mesh. This sounds a lot like "mesh-to-geometry integral assembly mapping" as mentioned in [this DTK paper](https://www.casl.gov/sites/default/files/docs/DTK_slattery_wilson_pawlowski_MC_Proceedings_2013.pdf). Other than this general description, I haven't seen any specific documentation of this feature though. 

- Can anyone here provide some more information about this feature or direct me to an example problem?  

I'm working with DTK2.0 installed with libMesh adapters.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
