### ISSUE TITLE
NearestNeighborOperator_def.hpp search tree use inconsistent with ArborX_DistributedSearchTree.hpp

### ISSUE THREAD

**Issue by mattbement** [ORNL-CEES/DataTransferKit#575]
https://github.com/ORNL-CEES/DataTransferKit/blob/2ffa27babf694737cba147fd66842dba1f586a87/packages/Meshfree/src/DTK_NearestNeighborOperator_def.hpp#L36-L37
is not consistent with  ArborX_DistributedSearchTree.hpp, at least for the ArborX hash that's in the repo.

**Comment by aprokop** [comment]
@mattbement How is it not consistent? There is an overload for `DistributedSearchTree`.

**Comment by mattbement** [comment]
Nevermind - I was misinterpreting a compiler error message.  Relative to an older version of DTK, I had to add ::device_type to my Kokkos::HostSpace template paramater.

**Comment by dalg24** [comment]
Related to arborx/ArborX#349
