### ISSUE TITLE
 Spline Operator

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#577]
I have extracted the equations we need to implement from Stuart's paper:
`Mesh-free data transfer algorithms for partitioned multiphysics problems: Conservation, accuracy, and
parallelism`. The equations are in the following file: [spline.pdf](https://github.com/ORNL-CEES/DataTransferKit/files/5043409/spline.pdf)

**Comment by sslattery** [comment]
Note there were some tricks to get this to scale for the off-diagonal blocks. Also you could apply some of the scaling you guys did in moving least squares which should make the linear solve better condition.
