### ISSUE TITLE
Decide on version to use for xSDK release

### ISSUE THREAD

**Issue by masterleinad** [ORNL-CEES/DataTransferKit#586]
It seems that both `master` and 3.1-rc1 are currently failing for xSDK (https://github.com/xsdk-project/xsdk-issues/issues/108#issuecomment-694401442). We should figure out what we want to have in the xSDK release and fix the issues.

**Comment by aprokop** [comment]
Aren't they failing because of the missing submodule?

**Comment by masterleinad** [comment]
I haven't checked yet what needs to be done.

**Comment by aprokop** [comment]
From what i see in spack, submodules are only enabled when cloning master branch. Versions are pulling releases. As releases done using github, they likely don't contains tribits submodule.

**Comment by masterleinad** [comment]
I think we just need to add the additional dependencies introduced for the SplineInterpolationOperator to the spack package or use a commit before that. I am not quite sure if we should have a tagged commit for that or not.

**Comment by aprokop** [comment]
Agreed about dependencies, and we probably should tag and make a release, making those dependencies version dependent.

**Comment by masterleinad** [comment]
I'm building it right now.

**Comment by masterleinad** [comment]
Anyone opposed to tagging the commit before SplineInterpolationOperator for a release to be used by xSDK? That would likely be easiest.
