### ISSUE TITLE
Compile error in DTK_SplineOperator_SERIAL.cpp 

### ISSUE THREAD

**Issue by gahansen** [ORNL-CEES/DataTransferKit#587]
I am compiling VOTD DTK (64e2257) against VOTD Trilinos (4fc95b9), and I have encountered a compilation error after configuring a base build using the options:

    ...
    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit" \
    -D Trilinos_ENABLE_DataTransferKit=ON \
    -D DataTransferKit_ENABLE_DBC=ON \
    -D DataTransferKit_ENABLE_TESTS=ON \
    -D DataTransferKit_ENABLE_EXAMPLES=ON \
    ...

I have attached the full output of the compile below.

I'm on a RHEL7 system using either Clang or GCC 10 (both show this error).

[DTK_compile.txt](https://github.com/ORNL-CEES/DataTransferKit/files/5386964/DTK_compile.txt)

**Comment by Rombur** [comment]
Thanks for reporting the issue. This looks like a bug in our end.  

I see in the path of the directory that you are using that you are working with albany. Albany uses `DTK 2.0` and the bug is in `master`. `DTK 2.0` and `master` are not compatible so make sure that you are using the correct version.

**Comment by gahansen** [comment]
Thanks Bruno. We're looking at using DTK-3.0 for some mesh to mesh transfer operations to support the Alegra project, I'm building in the Albany project space to leverage my Trilinos clone that I have in there already. Please let me know if I can pass on any more info on this, it looks like to core of DTK might have compiled and I might be in one of the tests or examples.
