### ISSUE TITLE
Compile error in ExodusProblemGenerator_def.hpp

### ISSUE THREAD

**Issue by gahansen** [ORNL-CEES/DataTransferKit#589]
I'm almost at the end of the base compile:

[100%] Building CXX object DataTransferKit/packages/Meshfree/test/CMakeFiles/DataTransferKit_NearestNeighborExodusGenerator.dir/tstNearestNeighborExodusGenerator.cpp.o

Ran into the attached compilation error:

[output.txt](https://github.com/ORNL-CEES/DataTransferKit/files/5392292/output.txt)

Machine and compilers same as in #587

**Comment by aprokop** [comment]
Here's the actual error:
```
<snip>/DataTransferKit/packages/Meshfree/test/PointCloudProblemGenerator/ExodusProblemGenerator_def.hpp:208:54:
error: no matching function for call to 'ArborX::Details::Distributor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::createFromSends(Kokkos::View<int*, Kokkos::HostSpace>&)'
  208 |     int num_node_import = distributor.createFromSends( export_ranks );
```
