### ISSUE TITLE
Archive creation error - OSX 10.13.6

### ISSUE THREAD

**Issue by gahansen** [ORNL-CEES/DataTransferKit#590]
I am doing a DTK (8b8baa5) build inside Trilinos (4fc95b9), using OSX 10.13.6 and Apple LLVM version 10.0.0. Here are my DTK build options:

    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit" \
    -D Trilinos_ENABLE_DataTransferKit=ON \
    -D DataTransferKit_ENABLE_DBC=ON \
    -D DataTransferKit_ENABLE_TESTS=ON \
    -D DataTransferKit_ENABLE_EXAMPLES=ON \

It appears that during the build, I am trying to create an empty "libdtk_search.a" - here is the error I am seeing:

[ 97%] Linking CXX static library libdtk_search.a
cd /Users/gahanse/Codes/Trilinos/build/MPI_REL_INT/DataTransferKit/packages && /usr/local/bin/cmake -P CMakeFiles/dtk_search.dir/cmake_clean_target.cmake
cd /Users/gahanse/Codes/Trilinos/build/MPI_REL_INT/DataTransferKit/packages && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/dtk_search.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/ar Scr libdtk_search.a  
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [DataTransferKit/packages/libdtk_search.a] Error 1
make[1]: *** [DataTransferKit/packages/CMakeFiles/dtk_search.dir/all] Error 2
make: *** [all] Error 2

Any thoughts on what might be happening to me - did I miss configuring the compilation for the search objects?

**Comment by aprokop** [comment]
@gahansen Did you clone DTK with submodules? Is it possible that your `dtk/packages/Search is empty`?

**Comment by gahansen** [comment]
@aprokop , I used the

      git clone --recursive git@github.com:ORNL-CEES/DataTransferKit.git

command to clone. There is a lot of stuff under "DataTransferKit/packages/Search", here is the ls-lR:

[rec_ls.txt](https://github.com/ORNL-CEES/DataTransferKit/files/5393009/rec_ls.txt)

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
