### ISSUE TITLE
Compile issue with Fortran bindings using IBM XL

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#594]
See xsdk-project/xsdk-issues#94

**Comment by sethrj** [comment]
@dalg24 or @aprokop : I'm making time to debug this on Summit, but the [build documentation](https://datatransferkit.readthedocs.io/en/latest/install.html) seems out of date -- even the note in the docs about the configure possibly being out of date is out of date 😆 ("You can always refer to scripts/docker_cmake" which no longer exists.)

Can I replicate this with trilinos as a TPL? Is there an existing trilinos%xl installation on summit? (If so, I can't find it.) Thanks!

**Comment by aprokop** [comment]
I don't think any of us have built trilinos/dtk/arborx with xl on Summit. I'm pretty sure current version of arborx cannot even be built with xl (see arborx/ArborX#132). There's simply lack of interest in working around the fact that XL does not properly support C++14.

If we want to move forward, however, we need to figure out first which version of DTK was compiled in the xSDK issue. Judging by the Trilinos version there (12.18.1) and the dtk variants resources in the Spack's Trilinos, it should be [dtk 3.1-rc1](https://github.com/ORNL-CEES/DataTransferKit/releases/tag/3.1-rc1) (edfa050cd46e2274ab0a0b7558caca0079c2e4ca).

**Comment by sethrj** [comment]
So if Trilinos and DTK C++ won't build with XL, why is the complaint about the fortran wrapper failure?

**Comment by aprokop** [comment]
> So if Trilinos and DTK C++ won't build with XL, why is the complaint about the fortran wrapper failure?

Trilinos may build. And it's possible that that version of DTK may also build, but not certain. I cannot say anything for certain.

**Comment by masterleinad** [comment]
I would just ask @luszczek for his configuration with spack.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
