### ISSUE TITLE
Version 2 Release

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#72]
Version 2 of the code will be released prior to starting development on version 3. The following needs to be finished:

- [x] Merge all open pull requests
- [x] Create version 2 branch @rombur
- [x] Create a new website @rombur @dalg24 
- [x] Publish version 2 documentation and development version on the new website @rombur
- [x] Make clear in documentation and on front page README that the version 2 branch is a stable release and the master branch is for development and is subject to changing interfaces and data structures. @rombur @sslattery 
- [x] Update the front page README to link to the stable version and add link to the tarball @Rombur ur
- [x] Add version 2 to CI build system for any changes to branch and pull requests/bug fixes @dalg24
- [x] Create announce mailing list 
- [x] Announcement of version 2 release

**Comment by aprokop** [comment]
What are the current blockers for this?

**Comment by sslattery** [comment]
I have some pull requests with some bug fixes I need to get in. I think we decided to wait on the build issues for now.

**Comment by aprokop** [comment]
It would be nice to document what needs to be done so that we can track the progress.

**Comment by Rombur** [comment]
@sslattery anything blocking the announcement of version 2?

**Comment by sslattery** [comment]
yeah too many meetings haha. will do today

**Comment by aprokop** [comment]
Maybe update with Github DTK wiki?

**Comment by sslattery** [comment]
should we just get rid of the wiki?

**Comment by aprokop** [comment]
What was its original purpose?

**Comment by sslattery** [comment]
Not sure but it looks like it overlaps with our read the docs so we may want to delete it to avoid confusion and duplicated effort. Looks like it hasn't been updated since April. Any thoughts @dalg24 ?

**Comment by Rombur** [comment]
@dalg24 is on vacation in France for two weeks.

**Comment by dalg24** [comment]
I wouldn't bother with the wiki for now.  I agree with Stuart.
