### ISSUE TITLE
Code format

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/DataTransferKit#77]
- [x] Choose clang-format version and define a `.clang-format`configuration file [S & B]
- [x] Enforce the new format [D]
- [x] Coding style guidelines [S]

**Comment by dalg24** [comment]
Only guidelines are missing now.

**Comment by sslattery** [comment]
It would be cool if there was a way to automatically generate some from the clang format

**Comment by dalg24** [comment]
No, guidelines are different, these include naming convention for instance.

**Comment by sslattery** [comment]
Ah ok - I will work on that. Perhaps a page for ReadTheDocs?

**Comment by dalg24** [comment]
Exactly.

**Comment by dalg24** [comment]
This not highest priority though so I'm not opposed to put it in the backlog.
