### ISSUE TITLE
Entity bounding box tuple size is fixed to 6

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#79]
The current interface of Entity has
```c++
void boundingBox( Teuchos::Tuple<double,6>& bounds ) const;
```

Should not the the second argument be 2*physicalDimension()? Or is it just this way for simplicity and the last tuple values are simply not used for lower dimensions?

**Comment by sslattery** [comment]
Yes - the lower tuple values are simply unused. We could have instead used a dynamic sized array with 2*physicalDimension() but this lets us unroll for loops for bounding box operations.

**Comment by sslattery** [comment]
@aprokop Can you close this if your question is sufficiently answered? If not we can further discuss.
