### ISSUE TITLE
Add DTK_DEBUG environment variable

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#83]
Add a way for DTK to query environment variables. This would be useful for making more debug options available at run time, so that users wouldn't have to recompile their release build in order to get some useful debug information.

This is motivated by a recent decision to provide a similar functionality in Tpetra (see trilinos/Trilinos#688). Tpetra or Teuchos could in the future provide the API to query the environment (see trilinos/Trilinos#654).

**Comment by sslattery** [comment]
Per our discussion I am vary wary of system environment variables - especially those such as this that will substantially affect performance. Although I agree that the use case is valid and could potentially be beneficial to the user, the negative aspects of this approach far outweigh the positive aspects.

**Comment by aprokop** [comment]
I'm still not 100% sure of your concerns. Is your concern only about the time it takes to query the environment variable? What if that is done only once in the beginning of the program, and sets some global parameter that is later queried? In this case, it does not affect the performance.

**Comment by sslattery** [comment]
The issue is, as @Rombur pointed out yesterday is that as soon is you start incorporating any environment variables into the mix you add an additional quagmire of configuration and runtime issues. I am not interested in support user configurations that additionally include environment variables. I would rather advocate for configure-only option. If the user wants debug information they should do a debug build.

**Comment by sslattery** [comment]
Basically I am saying I want zero environment variables in the code. I think they are a bad design choice and break the encapsulation provided by the configuration system.

**Comment by aprokop** [comment]
I guess it all boils down whether all DTK users running simulations can recompile DTK. If yes, then it does not matter. If no, then it would make our life easier to debug failed runs.

**Comment by Rombur** [comment]
I am with @sslattery. I find environment variables to be a real headache. Since up to now, nobody complained about not being able to recompile DTK when they hit a bug, I don't think it is necessary to introduce such a variable.

**Comment by aprokop** [comment]
OK, closing the issue. Will reopen if we need it later. By that time it is likely we could take advantage of Tpetra/Teuchos functionality.
