### ISSUE TITLE
Create a master list of all parameters

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#92]
Parameters are spread out through DTK and there is no single validation place. We had a similar issue in MueLu. The solution was simple and very useful: create a single place for parameters organized that could be queried. The solution in MueLu was to store all parameters with default values and descriptions within a single xml file. That file was then processed through XSLT transformations to a) generate documentation; b) generate a singleton class for query. 

I would suggest DTK have something similar. We could also provide a list of valid entries, and then use the Master class to provide parameter validation.

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
