### ISSUE TITLE
Check examples in CI

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/DataTransferKit#93]
We need to check the examples during CI. Otherwise, we may break them without realizing it and since they are the first thing that a new user will look at, it will give a poor impression of DTK.

**Comment by dalg24** [comment]
- [ ] Cleanup DTKData detection by CMake
- [ ] Use submodule to clone DTKData
- [ ] Add documentation
- [ ] Make the examples run in the test regression
- [ ] Update Jenkins build script

**Comment by dalg24** [comment]
partially addressed by #95

**Comment by dalg24** [comment]
@sslattery Why are all the subdirectories commented in the [`ClassicDTK/example/CMakelists.txt`](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Adapters/ClassicDTK/example/CMakeLists.txt#L2)?

**Comment by sslattery** [comment]
These are holdovers from the original code. I am not sure any of them work any more

**Comment by sslattery** [comment]
Next steps:

1. Determine if examples can also be tests but still build when tests are turned off
2. If they can't be built when tests are deactivated, decide on another path to run tests
3. Refactor examples to a pass/fail status to allow for testing

**Comment by aprokop** [comment]
- ADD_TEST will generate test if and only if ENABLE_TESTING() is called
- CTest module will invoke ENABLE_TESTING() automatically when BUILD_TESTING is ON
- the macro TRIBITS_INCLUDE_CTEST_SUPPORT that gets invoked in TriBITS/tribits/core/package_arch/TribitsProjectImpl.cmake calls INCLUDE(CTest)
which turns BUILD_TESTING ON

In other words TriBITS calls ENABLE_TESTING regardless of all the ENABLE_TESTS logic,
therefore ADD_TEST will always be picked up

**Comment by sslattery** [comment]
ok so @dalg24 was right here? I haven't looked at it yet

**Comment by dalg24** [comment]
Then all that is left to do is replace all instance of TRIBITS_ADD_EXECUTABLE by TRIBITS_ADD_EXECUTABLE_AND_TEST (only occurs in Libmesh, STKMesh and Moab) and apply
```
diff --git a/scripts/docker_cmake b/scripts/docker_cmake
index 2509a52..00f47b1 100755
--- a/scripts/docker_cmake
+++ b/scripts/docker_cmake
@@ -38,7 +38,7 @@ ARGS=(
     -D Trilinos_ENABLE_DataTransferKit=ON
         -D DataTransferKit_ENABLE_DBC=ON
         -D DataTransferKit_ENABLE_TESTS=ON
-        -D DataTransferKit_ENABLE_EXAMPLES=OFF
+        -D DataTransferKit_ENABLE_EXAMPLES=ON
         -D DataTransferKit_ENABLE_ClangFormat=ON
     )
 cmake "${ARGS[@]}" $EXTRA_ARGS $TRILINOS_DIR
```

**Comment by sslattery** [comment]
kudos to @dalg24 for figuring this out
