### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#94]
We need to decide on the performance benchmark to be used to track performance.
- [x] Decide on algorithms
- [ ] Decide on whether to use a pre-existing mesh or to auto-generate
- [ ] Anything else

**Comment by sslattery** [comment]
Lets focus on these algorithms to start with:

1. L2 Projection
2. Consistent Interpolation
3. Spline Interpolation
4. Moving Least Square Reconstruction

Each presents their own challenges. L2 projection has an expensive search and a linear solve, consistent interpolation will help focus on matrix assembly, spline interpolation has a very large Thyra composite operator, and moving least square reconstruction has lots of LAPACK calls.

**Comment by sslattery** [comment]
Making low priority for now but priority will increase in the future as we move along in development.

**Comment by sslattery** [comment]
Lets also add a benchmark for search. We could close #97 and add a Nanoflann benchmark.

**Comment by aprokop** [comment]
Are we talking about benchmarking different implementations of `StaticSearchTree`? Like the time to do `nnSearch` or `radiusSearch` on a randomly distributed point clouds? I could copy `tstStaticSearchTree.cpp` and expand it for larger clouds.

**Comment by sslattery** [comment]
Will work with application teams to try to develop application specific benchmarks instead of algorithm specific benchmarks

**Comment by masterleinad** [comment]
`DataTransferKit` is going to be archived.
