### ISSUE TITLE
Nanoflann update

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#97]
Do we want to update it? If yes, we could snapshot the most recent version.
Btw, it has moved to https://github.com/jlblancoc/nanoflann from code.google.com.

**Comment by dalg24** [comment]
another job for git submodule ;)

**Comment by dalg24** [comment]
Looks like we are working out of [version 1.1.7](https://github.com/ORNL-CEES/DataTransferKit/blob/master/packages/Utils/src/Nanoflann/DTK_nanoflann.hpp#L66) and the latest release is 1.2.2.

**Comment by sslattery** [comment]
I'm not opposed to an update or a git submodule here. This will likely not get used in version 3, however, as it is CPU-only code.

**Comment by aprokop** [comment]
It would still be a good baseline to compare the performance of new threaded codes to.

**Comment by sslattery** [comment]
Good point. In fact it would be nice to have for unit testing. We can test the functionality and results of new implementations against nanoflann as a baseline.

**Comment by sslattery** [comment]
Do we still want to do an update here? Because we distribute it with the code I'm not sure its necessary as its meeting our needs. We will certainly keep it around for the reasons of performance and testing new search code as indicated above but its not clear we need to update the code to achieve that.

**Comment by sslattery** [comment]
One more ping on this. Either we need to make this a low priority issue in the backlog or close

**Comment by aprokop** [comment]
I would argue for backlog. I'd like to get it done eventually, as I think a submodule is the way to go. But as you say it is not strictly necessary.

**Comment by aprokop** [comment]
Irrelevant now.
